/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#111318",
        "surface-dim": "#111318",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#bac9cb",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        "outline": "#849395",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        "primary": "#88f5ff",
        "on-primary": "#00363a",
        "primary-container": "#00ddeb",
        "on-primary-container": "#005d63",
        "inverse-primary": "#006970",
        "secondary": "#aec6ff",
        "on-secondary": "#002e6a",
        "secondary-container": "#0361d1",
        "on-secondary-container": "#dbe4ff",
        "tertiary": "#ffdfb0",
        "on-tertiary": "#422c00",
        "tertiary-container": "#ffbc3b",
        "on-tertiary-container": "#6f4d00",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#aec6ff",
        "on-secondary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004396",
        "tertiary-fixed": "#ffdeab",
        "tertiary-fixed-dim": "#fdbb3a",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5f4100",
        "background": "#111318",
        "on-background": "#e2e2e8",
        "surface-variant": "#333539",
        "surface-deep": "#0D1015",
        "surface-default": "#11151C",
        "surface-elevated": "#151A22",
        "surface-high": "#1A2029",
        "research-violet": "#9B5CFF",
        "status-benign": "#00D99A",
        "status-warning": "#FFB800",
        "status-critical": "#FF4354",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "panel-gap": "16px",
        "gutter": "24px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "max-width": "1440px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "technical-label": ["JetBrains Mono", "monospace"],
        "technical-data": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
        "sans": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
